
#line 3 "lex.FF.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer FF_create_buffer
#define yy_delete_buffer FF_delete_buffer
#define yy_flex_debug FF_flex_debug
#define yy_init_buffer FF_init_buffer
#define yy_flush_buffer FF_flush_buffer
#define yy_load_buffer_state FF_load_buffer_state
#define yy_switch_to_buffer FF_switch_to_buffer
#define yyin FFin
#define yyleng FFleng
#define yylex FFlex
#define yylineno FFlineno
#define yyout FFout
#define yyrestart FFrestart
#define yytext FFtext
#define yywrap FFwrap
#define yyalloc FFalloc
#define yyrealloc FFrealloc
#define yyfree FFfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE FFrestart(FFin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int FFleng;

extern FILE *FFin, *FFout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up FFtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up FFtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via FFrestart()), so that the user can continue scanning by
	 * just pointing FFin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when FFtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int FFleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow FFwrap()'s to do buffer switches
 * instead of setting up a fresh FFin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void FFrestart (FILE *input_file  );
void FF_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE FF_create_buffer (FILE *file,int size  );
void FF_delete_buffer (YY_BUFFER_STATE b  );
void FF_flush_buffer (YY_BUFFER_STATE b  );
void FFpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void FFpop_buffer_state (void );

static void FFensure_buffer_stack (void );
static void FF_load_buffer_state (void );
static void FF_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER FF_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE FF_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE FF_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE FF_scan_bytes (yyconst char *bytes,int len  );

void *FFalloc (yy_size_t  );
void *FFrealloc (void *,yy_size_t  );
void FFfree (void *  );

#define yy_new_buffer FF_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        FFensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            FF_create_buffer(FFin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        FFensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            FF_create_buffer(FFin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define FFwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *FFin = (FILE *) 0, *FFout = (FILE *) 0;

typedef int yy_state_type;

extern int FFlineno;

int FFlineno = 1;

extern char *FFtext;
#define yytext_ptr FFtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up FFtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	FFleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[202] =
    {   0,
        0,    0,    0,    0,    2,    2,   86,   83,   84,   77,
       65,   83,   61,   83,   71,   72,   60,   57,   73,   58,
       74,   59,   79,   76,   75,   63,   62,   64,   78,   69,
       70,   66,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   67,   83,   68,
       13,    9,    8,   85,    2,    4,    3,   54,    0,    0,
        7,    0,   49,   51,   52,   81,    0,    1,    6,   80,
       79,   48,   56,   53,   55,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   35,   78,   78,   78,   78,
       78,   40,   78,   26,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   50,   13,   12,   10,   11,
        2,    3,    3,    5,    7,    0,   82,    6,   14,   78,
       78,   78,   78,   78,   78,   78,   18,   78,   78,   21,
       78,   78,   39,   78,   41,   22,   78,   78,   78,   78,
       19,   24,   78,   78,   20,   78,   78,   78,   15,   16,
       17,   78,   78,   31,   78,   78,   36,   78,   78,   78,
       78,   78,   78,   78,   23,   78,   78,   44,   45,   78,
       78,   30,   78,   78,   37,   38,   78,   47,   78,   78,
       78,   78,   78,   46,   78,   78,   78,   78,   27,   42,
       78,   32,   43,   29,   78,   34,   25,   78,   33,   28,

        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       24,   25,   26,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   22,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       22,   22,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    5,    1,    1,    1,    1,
        1,    5,    5,    1,    3,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[211] =
    {   0,
        0,    0,   52,   53,   56,   57,  259,  260,  260,  260,
      238,   58,  260,  250,  260,  260,  260,  245,  260,  242,
       46,   55,   57,  260,  260,   55,  234,  233,    0,  260,
      260,  260,   50,   40,   47,   51,   47,   61,   53,  221,
      209,  205,  216,   55,   43,  206,  211,  260,  193,  260,
        0,  260,  260,   54,    0,  260,   94,  260,  103,  240,
      107,   88,  260,  260,  260,   91,  104,  260,    0,  100,
      105,  260,  260,  260,  260,    0,  198,  201,  205,  212,
      198,  206,  192,   81,  203,    0,  190,  192,  195,  191,
      187,    0,   88,    0,  196,  193,   83,   96,  184,  183,

      190,  185,  177,  187,  186,  260,    0,  260,  260,  260,
        0,  116,  124,  260,  260,  206,  205,    0,    0,  174,
      178,  177,  178,  187,  182,  167,    0,  184,  179,    0,
      165,  181,    0,  162,    0,    0,  167,  159,  158,  157,
        0,  157,  166,  155,    0,  168,  168,  160,    0,    0,
        0,  165,  159,    0,  159,  147,    0,  161,  146,  155,
      144,  151,  144,  149,    0,  146,  155,    0,    0,  152,
      155,    0,  142,  143,    0,    0,  152,    0,  133,  135,
      142,  133,  130,    0,  120,  109,  109,   99,    0,    0,
       71,    0,    0,    0,   78,    0,    0,   35,    0,    0,

      260,  139,  144,  149,   59,  154,  159,  164,  169,  174
    } ;

static yyconst flex_int16_t yy_def[211] =
    {   0,
      201,    1,  202,  202,  203,  203,  201,  201,  201,  201,
      201,  204,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  205,  201,
      201,  201,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  201,  201,  201,
      206,  201,  201,  207,  208,  201,  209,  201,  204,  201,
      204,  204,  201,  201,  201,  201,  201,  201,  210,  201,
      201,  201,  201,  201,  201,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  205,  201,  206,  201,  201,  201,
      208,  209,  209,  201,  201,  201,  201,  210,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

        0,  201,  201,  201,  201,  201,  201,  201,  201,  201
    } ;

static yyconst flex_int16_t yy_nxt[315] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   30,    8,   31,   32,    8,   33,   34,
       35,   36,   37,   38,   29,   29,   39,   40,   41,   29,
       29,   29,   42,   29,   43,   44,   45,   29,   46,   47,
       29,   48,   49,   50,   52,   52,   53,   53,   56,   56,
       60,   66,   61,   76,   68,   57,   57,  200,   67,   69,
       70,  102,   71,   72,   73,   83,   54,   54,   67,   77,
       78,   81,   62,   85,   82,   87,   92,  103,   84,   89,
       60,   98,   86,   93,  109,   79,   80,   88,   99,   90,

      110,  100,   91,  113,  101,   60,   66,   61,  114,   60,
      199,   61,   62,   67,  116,   66,  116,  198,   70,  117,
       71,  126,   67,   67,  134,  201,  127,   62,  138,  139,
      201,   62,   67,  113,  135,  140,  141,  197,  114,   51,
       51,   51,   51,   51,   55,   55,   55,   55,   55,   59,
       59,   59,   59,   59,  107,  196,  195,  107,  107,  108,
      194,  108,  108,  108,  111,  193,  111,  192,  111,  112,
      191,  112,  112,  112,  118,  190,  118,  118,  118,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,

      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      117,  117,  148,  147,  146,  145,  144,  143,  142,  137,
      136,  133,  132,  131,  130,  129,  128,  125,  124,  123,
      122,  121,  120,  119,  115,  106,  105,  104,   97,   96,
       95,   94,   75,   74,   65,   64,   63,   58,  201,    7,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201
    } ;

static yyconst flex_int16_t yy_chk[315] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
       12,   21,   12,  205,   22,    5,    6,  198,   21,   22,
       23,   45,   23,   26,   26,   35,    3,    4,   21,   33,
       33,   34,   12,   36,   34,   37,   39,   45,   35,   38,
       62,   44,   36,   39,   54,   33,   33,   37,   44,   38,

       54,   44,   38,   57,   44,   59,   66,   59,   57,   61,
      195,   61,   62,   66,   67,   70,   67,  191,   71,   67,
       71,   84,   70,   66,   93,  112,   84,   59,   97,   97,
      112,   61,   70,  113,   93,   98,   98,  188,  113,  202,
      202,  202,  202,  202,  203,  203,  203,  203,  203,  204,
      204,  204,  204,  204,  206,  187,  186,  206,  206,  207,
      185,  207,  207,  207,  208,  183,  208,  182,  208,  209,
      181,  209,  209,  209,  210,  180,  210,  210,  210,  179,
      177,  174,  173,  171,  170,  167,  166,  164,  163,  162,
      161,  160,  159,  158,  156,  155,  153,  152,  148,  147,

      146,  144,  143,  142,  140,  139,  138,  137,  134,  132,
      131,  129,  128,  126,  125,  124,  123,  122,  121,  120,
      117,  116,  105,  104,  103,  102,  101,  100,   99,   96,
       95,   91,   90,   89,   88,   87,   85,   83,   82,   81,
       80,   79,   78,   77,   60,   49,   47,   46,   43,   42,
       41,   40,   28,   27,   20,   18,   14,   11,    7,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int FF_flex_debug;
int FF_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *FFtext;
#line 1 "FF.l"
#line 5 "FF.l"
#include <vector>

#include <string.h>
#include "AstNode.h"
#include "FF_yacc.h"

extern int my_yyinput(char *, int);

using namespace std;

#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r = my_yyinput(b, ms))

int yyline = 1;
char str_buf[1024];
char *str_buf_p;



#line 630 "lex.FF.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int FFlex_destroy (void );

int FFget_debug (void );

void FFset_debug (int debug_flag  );

YY_EXTRA_TYPE FFget_extra (void );

void FFset_extra (YY_EXTRA_TYPE user_defined  );

FILE *FFget_in (void );

void FFset_in  (FILE * in_str  );

FILE *FFget_out (void );

void FFset_out  (FILE * out_str  );

int FFget_leng (void );

char *FFget_text (void );

int FFget_lineno (void );

void FFset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int FFwrap (void );
#else
extern int FFwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( FFtext, FFleng, 1, FFout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( FFin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( FFin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, FFin))==0 && ferror(FFin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(FFin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int FFlex (void);

#define YY_DECL int FFlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after FFtext and FFleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 30 "FF.l"


#line 817 "lex.FF.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! FFin )
			FFin = stdin;

		if ( ! FFout )
			FFout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			FFensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				FF_create_buffer(FFin,YY_BUF_SIZE );
		}

		FF_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of FFtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 202 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 201 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "FF.l"
BEGIN(COMMENT);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "FF.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "FF.l"

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 36 "FF.l"
yyline++;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "FF.l"
BEGIN(INITIAL);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "FF.l"
{}
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up FFtext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up FFtext again */
YY_RULE_SETUP
#line 41 "FF.l"
{
    str_buf_p=str_buf;
    *str_buf_p='\0';
    BEGIN (STRING);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "FF.l"
{
  *str_buf_p='\0';
  FFlval.strVal=str_buf;
  BEGIN(INITIAL);
  return TOK_STRING_CONST;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 54 "FF.l"
{
  BEGIN(INITIAL);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "FF.l"
{
  *str_buf_p++='\n';
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "FF.l"
{
  *str_buf_p++='\t';
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "FF.l"
{
  *str_buf_p++=FFtext[1];
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "FF.l"
{
  char *p=FFtext;
  while(*p)
    *str_buf_p++=*p++;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "FF.l"
{
   return TOK_ABS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 80 "FF.l"
{
   return TOK_ACOS;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "FF.l"
{
   return TOK_ASIN;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 88 "FF.l"
{
   return TOK_ATAN;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "FF.l"
{
   return TOK_COS;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "FF.l"
{
   return TOK_SIN;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "FF.l"
{
   return TOK_TAN;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 104 "FF.l"
{
   return TOK_EXP;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "FF.l"
{
   return TOK_LOG;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "FF.l"
{
   return TOK_SQRT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "FF.l"
{
   return TOK_SQR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "FF.l"
{
   return TOK_INITIAL;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "FF.l"
{
   return TOK_KC;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "FF.l"
{
   return TOK_RESULT;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 132 "FF.l"
{
   return TOK_SIMULATE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "FF.l"
{
    return TOK_BOOLEAN;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 140 "FF.l"
{
    return TOK_BREAK;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "FF.l"
{
    return TOK_CASE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "FF.l"
{
    return TOK_STRING;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 152 "FF.l"
{
    return TOK_CONTINUE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 156 "FF.l"
{
    return TOK_DEFAULT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 160 "FF.l"
{
    return TOK_DO;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "FF.l"
{
    return TOK_ELSE;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "FF.l"
{
    return TOK_FALSE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 172 "FF.l"
{
    return TOK_FLOAT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 176 "FF.l"
{
    return TOK_FOR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 180 "FF.l"
{
    return TOK_IF;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 184 "FF.l"
{
    return TOK_INT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 188 "FF.l"
{
    return TOK_RETURN;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 192 "FF.l"
{
    return TOK_SWITCH;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 196 "FF.l"
{
    return TOK_TRUE;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 200 "FF.l"
{
    return TOK_VOID;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 204 "FF.l"
{
    return TOK_WHILE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 208 "FF.l"
{
    return TOK_PRINT;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 212 "FF.l"
{
    return TOK_LEFT_SHIFT;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 216 "FF.l"
{
    return TOK_AND;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 220 "FF.l"
{
    return TOK_OR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 224 "FF.l"
{
    return TOK_PLUS_PLUS;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 228 "FF.l"
{
    return TOK_MINUS_MINUS;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 232 "FF.l"
{
    return TOK_EQ;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 236 "FF.l"
{
    return TOK_NE;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 240 "FF.l"
{
    return TOK_GE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 244 "FF.l"
{
    return TOK_LE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "FF.l"
{
        return TOK_PLUS;
     }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 252 "FF.l"
{
        return TOK_MINUS;
     }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 256 "FF.l"
{
        return TOK_DIV;
     }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 260 "FF.l"
{
        return TOK_MULT;
     }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 264 "FF.l"
{
        return TOK_MOD;
     }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 268 "FF.l"
{
        return TOK_ASSIGN;
     }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 272 "FF.l"
{
        return TOK_LT;
     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 276 "FF.l"
{
        return TOK_GT;
     }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 280 "FF.l"
{
        return TOK_NOT;
     }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 284 "FF.l"
{
       return TOK_EXPONENT;
     }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 288 "FF.l"
{
    return TOK_LBRACE;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 292 "FF.l"
{
    return TOK_RBRACE;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 296 "FF.l"
{
    return TOK_LBRACK;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 300 "FF.l"
{
    return TOK_RBRACK;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 304 "FF.l"
{
    return TOK_LPAREN;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 308 "FF.l"
{
    return TOK_RPAREN;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 312 "FF.l"
{
    return TOK_COMMA;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 316 "FF.l"
{
    return TOK_DOT;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 320 "FF.l"
{
    return TOK_SEMICOLON;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 324 "FF.l"
{
    return TOK_COLON;
}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 328 "FF.l"
{
    yyline++;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 332 "FF.l"
{
    FFlval.strVal = new char[strlen(FFtext)+1];
    strcpy(FFlval.strVal, FFtext);
    return TOK_ID;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 338 "FF.l"
{
    FFlval.intVal = atol(FFtext);
    return TOK_INT_CONST;
}
	YY_BREAK
case 80:
#line 344 "FF.l"
case 81:
#line 345 "FF.l"
case 82:
YY_RULE_SETUP
#line 345 "FF.l"
{
    sscanf(FFtext, "%lf", &FFlval.floatVal);
    return TOK_FLOAT_CONST;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 350 "FF.l"
{
    FFlval.strVal=FFtext;
    return TOK_SYNTAX_ERROR;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 355 "FF.l"
{}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 357 "FF.l"
ECHO;
	YY_BREAK
#line 1484 "lex.FF.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed FFin at a new source and called
			 * FFlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = FFin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( FFwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * FFtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of FFlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					FFrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			FFrestart(FFin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) FFrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 202 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 202 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 201);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up FFtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					FFrestart(FFin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( FFwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve FFtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void FFrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        FFensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            FF_create_buffer(FFin,YY_BUF_SIZE );
	}

	FF_init_buffer(YY_CURRENT_BUFFER,input_file );
	FF_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void FF_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		FFpop_buffer_state();
	 *		FFpush_buffer_state(new_buffer);
     */
	FFensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	FF_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (FFwrap()) processing, but the only time this flag
	 * is looked at is after FFwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void FF_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	FFin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE FF_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) FFalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in FF_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) FFalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in FF_create_buffer()" );

	b->yy_is_our_buffer = 1;

	FF_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with FF_create_buffer()
 * 
 */
    void FF_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		FFfree((void *) b->yy_ch_buf  );

	FFfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a FFrestart() or at EOF.
 */
    static void FF_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	FF_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then FF_init_buffer was _probably_
     * called from FFrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void FF_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		FF_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void FFpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	FFensure_buffer_stack();

	/* This block is copied from FF_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from FF_switch_to_buffer. */
	FF_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void FFpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	FF_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		FF_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void FFensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)FFalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in FFensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)FFrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in FFensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE FF_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) FFalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in FF_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	FF_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to FFlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       FF_scan_bytes() instead.
 */
YY_BUFFER_STATE FF_scan_string (yyconst char * yystr )
{
    
	return FF_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to FFlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE FF_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) FFalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in FF_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = FF_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in FF_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up FFtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		FFtext[FFleng] = (yy_hold_char); \
		(yy_c_buf_p) = FFtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		FFleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int FFget_lineno  (void)
{
        
    return FFlineno;
}

/** Get the input stream.
 * 
 */
FILE *FFget_in  (void)
{
        return FFin;
}

/** Get the output stream.
 * 
 */
FILE *FFget_out  (void)
{
        return FFout;
}

/** Get the length of the current token.
 * 
 */
int FFget_leng  (void)
{
        return FFleng;
}

/** Get the current token.
 * 
 */

char *FFget_text  (void)
{
        return FFtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void FFset_lineno (int  line_number )
{
    
    FFlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see FF_switch_to_buffer
 */
void FFset_in (FILE *  in_str )
{
        FFin = in_str ;
}

void FFset_out (FILE *  out_str )
{
        FFout = out_str ;
}

int FFget_debug  (void)
{
        return FF_flex_debug;
}

void FFset_debug (int  bdebug )
{
        FF_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from FFlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    FFin = stdin;
    FFout = stdout;
#else
    FFin = (FILE *) 0;
    FFout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * FFlex_init()
     */
    return 0;
}

/* FFlex_destroy is for both reentrant and non-reentrant scanners. */
int FFlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		FF_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		FFpop_buffer_state();
	}

	/* Destroy the stack itself. */
	FFfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * FFlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *FFalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *FFrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void FFfree (void * ptr )
{
	free( (char *) ptr );	/* see FFrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 357 "FF.l"



