#############################################################################
# Makefile for building: network_tools
# Generated by qmake (2.01a) (Qt 4.4.3) on: Sat Mar 14 20:56:51 2009
# Project:  network_tools.pro
# Template: subdirs
# Command: /usr/local/Trolltech/Qt-4.4.3/bin/qmake -unix -o Makefile network_tools.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/Trolltech/Qt-4.4.3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libfitness \
		sub-libgui \
		sub-libnetwork \
		sub-network_editor \
		sub-fh_evolve \
		sub-ga_ode_opt

libfitness/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libfitness/ || $(MKDIR) libfitness/ 
	cd libfitness/ && $(QMAKE) libfitness.pro -unix -o $(MAKEFILE)
sub-libfitness-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libfitness/ || $(MKDIR) libfitness/ 
	cd libfitness/ && $(QMAKE) libfitness.pro -unix -o $(MAKEFILE)
sub-libfitness: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE)
sub-libfitness-make_default: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) 
sub-libfitness-make_first: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) first
sub-libfitness-all: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) all
sub-libfitness-clean: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) clean
sub-libfitness-distclean: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libfitness-install_subtargets: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) install
sub-libfitness-uninstall_subtargets: libfitness/$(MAKEFILE) FORCE
	cd libfitness/ && $(MAKE) -f $(MAKEFILE) uninstall
libgui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libgui/ || $(MKDIR) libgui/ 
	cd libgui/ && $(QMAKE) libgui.pro -unix -o $(MAKEFILE)
sub-libgui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libgui/ || $(MKDIR) libgui/ 
	cd libgui/ && $(QMAKE) libgui.pro -unix -o $(MAKEFILE)
sub-libgui: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE)
sub-libgui-make_default: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) 
sub-libgui-make_first: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) first
sub-libgui-all: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) all
sub-libgui-clean: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) clean
sub-libgui-distclean: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libgui-install_subtargets: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) install
sub-libgui-uninstall_subtargets: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) uninstall
libnetwork/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libnetwork/ || $(MKDIR) libnetwork/ 
	cd libnetwork/ && $(QMAKE) libnetwork.pro -unix -o $(MAKEFILE)
sub-libnetwork-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libnetwork/ || $(MKDIR) libnetwork/ 
	cd libnetwork/ && $(QMAKE) libnetwork.pro -unix -o $(MAKEFILE)
sub-libnetwork: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE)
sub-libnetwork-make_default: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) 
sub-libnetwork-make_first: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) first
sub-libnetwork-all: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) all
sub-libnetwork-clean: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) clean
sub-libnetwork-distclean: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libnetwork-install_subtargets: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) install
sub-libnetwork-uninstall_subtargets: libnetwork/$(MAKEFILE) FORCE
	cd libnetwork/ && $(MAKE) -f $(MAKEFILE) uninstall
network_editor/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) network_editor/ || $(MKDIR) network_editor/ 
	cd network_editor/ && $(QMAKE) network_editor.pro -unix -o $(MAKEFILE)
sub-network_editor-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) network_editor/ || $(MKDIR) network_editor/ 
	cd network_editor/ && $(QMAKE) network_editor.pro -unix -o $(MAKEFILE)
sub-network_editor: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE)
sub-network_editor-make_default: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) 
sub-network_editor-make_first: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) first
sub-network_editor-all: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) all
sub-network_editor-clean: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) clean
sub-network_editor-distclean: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) distclean
sub-network_editor-install_subtargets: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) install
sub-network_editor-uninstall_subtargets: network_editor/$(MAKEFILE) FORCE
	cd network_editor/ && $(MAKE) -f $(MAKEFILE) uninstall
fh_evolve/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) fh_evolve/ || $(MKDIR) fh_evolve/ 
	cd fh_evolve/ && $(QMAKE) fh_evolve.pro -unix -o $(MAKEFILE)
sub-fh_evolve-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) fh_evolve/ || $(MKDIR) fh_evolve/ 
	cd fh_evolve/ && $(QMAKE) fh_evolve.pro -unix -o $(MAKEFILE)
sub-fh_evolve: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE)
sub-fh_evolve-make_default: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) 
sub-fh_evolve-make_first: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) first
sub-fh_evolve-all: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) all
sub-fh_evolve-clean: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) clean
sub-fh_evolve-distclean: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) distclean
sub-fh_evolve-install_subtargets: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) install
sub-fh_evolve-uninstall_subtargets: fh_evolve/$(MAKEFILE) FORCE
	cd fh_evolve/ && $(MAKE) -f $(MAKEFILE) uninstall
ga_ode_opt/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ga_ode_opt/ || $(MKDIR) ga_ode_opt/ 
	cd ga_ode_opt/ && $(QMAKE) ga_ode_opt.pro -unix -o $(MAKEFILE)
sub-ga_ode_opt-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ga_ode_opt/ || $(MKDIR) ga_ode_opt/ 
	cd ga_ode_opt/ && $(QMAKE) ga_ode_opt.pro -unix -o $(MAKEFILE)
sub-ga_ode_opt: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE)
sub-ga_ode_opt-make_default: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) 
sub-ga_ode_opt-make_first: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) first
sub-ga_ode_opt-all: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) all
sub-ga_ode_opt-clean: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) clean
sub-ga_ode_opt-distclean: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ga_ode_opt-install_subtargets: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) install
sub-ga_ode_opt-uninstall_subtargets: ga_ode_opt/$(MAKEFILE) FORCE
	cd ga_ode_opt/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: network_tools.pro  /usr/local/Trolltech/Qt-4.4.3/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile network_tools.pro
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile network_tools.pro

qmake_all: sub-libfitness-qmake_all sub-libgui-qmake_all sub-libnetwork-qmake_all sub-network_editor-qmake_all sub-fh_evolve-qmake_all sub-ga_ode_opt-qmake_all FORCE

make_default: sub-libfitness-make_default sub-libgui-make_default sub-libnetwork-make_default sub-network_editor-make_default sub-fh_evolve-make_default sub-ga_ode_opt-make_default FORCE
make_first: sub-libfitness-make_first sub-libgui-make_first sub-libnetwork-make_first sub-network_editor-make_first sub-fh_evolve-make_first sub-ga_ode_opt-make_first FORCE
all: sub-libfitness-all sub-libgui-all sub-libnetwork-all sub-network_editor-all sub-fh_evolve-all sub-ga_ode_opt-all FORCE
clean: sub-libfitness-clean sub-libgui-clean sub-libnetwork-clean sub-network_editor-clean sub-fh_evolve-clean sub-ga_ode_opt-clean FORCE
distclean: sub-libfitness-distclean sub-libgui-distclean sub-libnetwork-distclean sub-network_editor-distclean sub-fh_evolve-distclean sub-ga_ode_opt-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libfitness-install_subtargets sub-libgui-install_subtargets sub-libnetwork-install_subtargets sub-network_editor-install_subtargets sub-fh_evolve-install_subtargets sub-ga_ode_opt-install_subtargets FORCE
uninstall_subtargets: sub-libfitness-uninstall_subtargets sub-libgui-uninstall_subtargets sub-libnetwork-uninstall_subtargets sub-network_editor-uninstall_subtargets sub-fh_evolve-uninstall_subtargets sub-ga_ode_opt-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

