######################################################################
# Automatically generated by qmake (1.07a) Sat Mar 17 08:14:27 2007
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += parse.cpp
